title: Guilherme Oliveira
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog"
url: "https://gueepo.me"

# Author Settings
author: Guilherme Oliveira # add your name
author-img: me.jpg # add your photo
about-author: Computer Science Student, working with Automated Tests. Hobbyist Game Developer.
twitter: guilhermepo2
github: guilhermepo2
linkedin: guilhermepo2
email: guilherme.061@gmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
