title: Guilherme Oliveira
description: > # this means to ignore newlines until "baseurl:"
  Guilherme Oliveira's Blog, here is the place I talk about a bunch of things, technology,
  games, game design, gaming, random stuff, whatever, welcome!
permalink: ':title/'
baseurl: "/blog"
url: "https://gueepo.me"

# Author Settings
author: Guilherme Oliveira # add your name
author-img: portrait.png # add your photo
about-author: Computer Science Ungraduate. Gameplay Programmer.
twitter: guilhermepo2
github: guilhermepo2
linkedin: guilhermepo2
email: guilherme.061@gmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
